### ISSUE TITLE
Currently does not inject dependencies names with "resolve"

### ISSUE THREAD

**Issue by laurent-le-graverend** [btford/ngmin#53] opened 2013-09-28 08:27 UTC
It does not inject the dependencies on the following case:

We are losing $q and $timeout

``` javascript
  angular.module('myApp', []).config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'views/quiz.html',
      controller: 'QuizCtrl',
      resolve: {
        delay: function($q, $timeout) {
          var delay;
          delay = $q.defer();
          $timeout(delay.resolve, 100);
          return delay.promise;
        }
      }
    }).otherwise({
      redirectTo: '/'
    });
  })
```

Generate:

``` javascript
  delay: function (a, b) {
    var c;
    return c = a.defer(), b(c.resolve, 100), c.promise;
  }
```

**Comment by lsiv568** [comment] 2013-10-09 17:02
:+1:

**Comment by sathify** [comment] 2013-10-16 20:15
+1. Having the same problem. Any way to overcome this until ng-min is able to inject dependencies into the 'resolve' function?

**Comment by lsiv568** [comment] 2013-10-16 20:41
Use the inline annotation DI syntax as shown below.  This is what ngmin converts inferred DI syntax to.

``` javascript
resolve: {
  delay: ['$q', '$timeout', function($q, $timeout) {
    var delay;
    delay = $q.defer();
    $timeout(delay.resolve, 100);
      return delay.promise;
  }]
}
```

**Comment by eddiemonge** [comment] 2013-10-22 18:31
Duplicate of https://github.com/btford/ngmin/issues/35

**Comment by aikoven** [comment] 2014-03-28 10:51
For now resolved this by putting these lines in package.json

```
"devDependencies": {
  "ngmin": "git+https://github.com/werk85/ngmin.git",
  "astral-angular-annotate": "git+https://github.com/werk85/astral-angular-annotate.git",
  "astral-angular-annotate-ui-router": "git+https://github.com/werk85/astral-angular-annotate-ui-router.git",
  "grunt-ngmin": "0.0.3",
  ...
}
```

**Closed as completed** 2014-03-28 17:17 UTC
