### ISSUE TITLE
directive controller isn't getting annotated

### ISSUE THREAD

**Issue by alexgorbatchev** [btford/ngmin#27] opened 2013-04-27 03:57 UTC
```
app.directive('tag', function () {
  return {
    controller: function ($scope, $rootScope, $routeParams) {
    }
  }
});
```

doesn't get annotated :(

**Comment by btford** [comment] 2013-04-27 04:01
Please check existing issues before filing another. Thanks!

Duplicate of #21.

**Closed as completed by btford** 2013-04-27 04:01 UTC
Labels: duplicate
