### ISSUE TITLE
ngmin reformats code, e.g. comments

### ISSUE THREAD

**Issue by raDiesle** [btford/ngmin#76] opened 2014-02-25 13:08 UTC
Hi,

for grunt-replace I used  var config = "default";// REGEX_MATCHER
but ngmin will break myregex, because it will result in:
var config = "default";
// REGEX_MATCHER

ngmin should not reformat code, I think.

**Comment by btford** [comment] 2014-03-03 03:53
This is a duplicate of #60. Please check the existing issues and PRs before posting next time. Thanks!

**Closed as completed by btford** 2014-03-03 03:53 UTC
Labels: duplicate

**Comment by seriema** [comment] 2014-04-26 13:24
This isn't a duplicate? This says the comments gets moved, not _re_moved.
