### ISSUE TITLE
ngmin does not work on config calls

### ISSUE THREAD

**Issue by mlegenhausen** [btford/ngmin#10] opened 2013-02-28 15:00 UTC
I tryed your `generator-angular` project and noticed that the `config` call is not annotated. I already updated the `ngmin` dependency of `grunt-ngmin` to the latest version on github without success. I also saw that you already added `config` to your `signature.js`. The following code is not annotated (from your angular generator project):

```
angular.module('app', []).config(function ($routeProvider) {
  $routeProvider.when('/', {
    templateUrl: 'views/main.html',
    controller: 'MainCtrl'
  }).otherwise({ redirectTo: '/' });
});
```

**Comment by btford** [comment] 2013-03-04 03:47
Fixed in 6f096e0f55d59318baba34a1ae133c68a5b10408.

Thanks!

**Closed as completed by btford** 2013-03-04 03:47 UTC

**Comment by gregwebs** [comment] 2013-03-09 01:29
just saw this, I am assuming it is not on npm yet.

**Comment by btford** [comment] 2013-03-10 05:12
should be as `v0.3.0`.

**Comment by gregwebs** [comment] 2013-03-10 08:08
thanks, I think I was actually seeing the other issue I opened

**Comment by jszmajda** [comment] 2013-06-10 02:15
Looks like this might've regressed with the move to astral? I'm not seeing my config vars get handled appropriately with ngmin 0.4.0

EDIT: also having trouble with directives. FWIW I'm using the pattern (due to coffeescript)

``` javascript
var m;
m = angular.module('whatever', [])
m.directive('something', function(injectable){
  ...
})
```

**Comment by BinaryMuse** [comment] 2013-06-19 00:03
@joshsz I'm unable to reproduce this with ngmin 0.4.0:

```
$ node
> ngmin = require('ngmin')
{ annotate: [Function] }
> ngmin.annotate("var m; m = angular.module('whatever', []); m.directive('something', function(injectable){});")
'var m;\nm = angular.module(\'whatever\', []);\nm.directive(\'something\', [\n  \'injectable\',\n  function (injectable) {\n  }\n]);'
```
