### ISSUE TITLE
Manually specify a function to be turned into DI-compatible array

### ISSUE THREAD

**Issue by msafi** [btford/ngmin#75] opened 2014-02-19 12:59 UTC
I know ngMin is intended to work with mostly conventional code, but I'd like to propose the following:

There are situations where a function would need to be annotated as a DI-compatible array in non-standard places. For example, in my `ui-router`, I have code that looks like this:

``` js
statesConfig.appDetails.resolve = {
  appDetails: function(appLookup, $stateParams) {
    ...
  }
}
```

Then I pass that object to my `$stateProvider` like so:

``` js
$stateProvider
  .state('annotate', statesConfig.appDetails)
```

I think this is not an improper way of doing things. Yet, it doesn't work with `ngMin`. 

Could there be a way to manually specify a function to be turned into a DI-compatible array? Like:

``` js
statesConfig.appDetails.resolve = {
  /** ngMin **/
  appDetails: function(appLookup, $stateParams) {
    ...
  }
}
```

**Comment by btford** [comment] 2014-03-03 05:18
AFAICT, this is a duplicate of #61.

**Closed as completed by btford** 2014-03-03 05:18 UTC
Labels: duplicate
