### ISSUE TITLE
Support inline function passing to $httpProvider.interceptors.push

### ISSUE THREAD

**Issue by fitzchak** [btford/ngmin#82] opened 2014-03-07 09:32 UTC
```
.config(function($httpProvider) {
    $httpProvider.interceptors.push(function($rootScope, $q, httpBuffer) {
      return {
        responseError: function(rejection) {
          if (rejection.status === 401 && !rejection.config.ignoreAuthModule) {
            var deferred = $q.defer();
            httpBuffer.append(rejection.config, deferred);
            $rootScope.$broadcast('event:auth-loginRequired', rejection);
            return deferred.promise;
          }
          // otherwise, default behavior
          return $q.reject(rejection);
        }
      };
    });
  });
```

**Comment by eekboom** [comment] 2014-03-13 16:44
Duplicate of #59 ?!

**Comment by fitzchak** [comment] 2014-03-13 19:40
Yes...

**Comment by btford** [comment] 2014-03-13 19:44
@fitzchak please check existing issues before creating new ones. Thanks!

**Closed as completed by btford** 2014-03-13 19:44 UTC
Labels: duplicate
